### ISSUE TITLE
What could be wrong ?

### ISSUE THREAD

**Issue by Freeman656** [zibous/ha-watermeter#14]
Hi,
I've successfully installed and wired the Wemos D1 Mini + CC1101 on esphome and the wifi communication gives me some logs.
No error visible.
But I don't get any communication from my water sensor (izar rc 868 i r4, not the PL one, does it make a difference ?).
The water sensor is underground about 50cm, and the D1mini about 20m from it in the house (the closest it can be with wifi connected).
This communication is supposed to be 500m and/or 1500m range, so I guess it's fine even underground ?

Moreover, in the documentation of the wiring (https://github.com/zibous/ha-watermeter/blob/master/esphome/watermeter_d1mini.md), there is an inconsistency for the GD02 -> D1 and GD00 -> D2 which is not the same in the picture wiring (GD02 -> D2 and GD00 -> D1), so which one is right ? I even tried both without success.

Is there any way of checking if the CC1101 is working fine ?

Thanks for your help.
Cédric

**Comment by zibous** [comment]
> Moreover, in the documentation of the wiring (https://github.com/zibous/ha-watermeter/blob/master/esphome/watermeter_d1mini.md), there is an inconsistency for the GD02 -> D1 and GD00 -> D2 which is not the same in the picture wiring (GD02 -> D2 and GD00 -> D1), so which one is right ? I even tried both without success.

ohhh thanks, the wiring picture is wrong.

```
 gdo0_pin: GPIO04 #D2  High Impedance
 gdo2_pin: GPIO05 #D1  High Impedance
```

> Is there any way of checking if the CC1101 is working fine ?

- use watermeterID: 0
- set loglevel to DEBUG or VERBOSE

> Note: I have 2 D1MINI and they are wired indent and have the same hardware and from the same supplier and same order. One works fine and the other always boots with a JSON error. The ESP32 variant works w/o theese errors.

**Comment by zibous** [comment]
Hi,

I did some tests and found that only the WEMOS D1 works for me. 

If you don't get any data, but the CC1101 is recognized correctly, it may be due to the gdo0_pin/gdo2_pin wiring. 

If they are swapped, then no values come. 

Since the Wemos D1 Mini  is critical, I would recommend the ESP32 variant.

see: <https://github.com/zibous/ha-watermeter#wemos-d1mini--vs-esp32-v4>

**Comment by Freeman656** [comment]
I don't have any JSON error with the D1 mini, but I'm using the D1 mini v4.0.0 (new style/component, and more memory). So I guess it should be OK.
I also tested on NodeMCUv3 which give me the same results, no data coming from the water meter.
Maybe I'm too far away from the water meter, I don't know, I'll try to next to it and let you know.

**Comment by zibous** [comment]
Hi
> I don't have any JSON error with the D1 mini, but I'm using the D1 mini v4.0.0 (new style/component, and more memory).

this one : https://opencircuit.shop/product/wemos-d1-mini-v4.0-wifi-module

w/o Data you can'nt see the JSON ERROR.
Do you use the latest D1Mini Test YAML ?
https://github.com/zibous/ha-watermeter/blob/master/esphome/wm-d1mini-test.yaml

Can you post your Logmessages with loglevel "DEBUG" or "VERBOSE".

**Comment by Freeman656** [comment]
Yes, the D1 mini is this one, but a chinese copy from ali I think...
I'm using the yaml from a few days ago, not this one.
Please find the logs attached.

[logs_wmbus-minid1_logs.txt](https://github.com/zibous/ha-watermeter/files/11364007/logs_wmbus-minid1_logs.txt)

**Comment by zibous** [comment]
OK.

1. Please use the latest wm-d1mini-test.yaml:
   Because your installation is old: `'project_version = 1.1.7`
   https://github.com/zibous/ha-watermeter/blob/master/esphome/wm-d1mini-test.yaml
   this one uses the latest wbmus component from github

3. Before install make a  ' Clean Build files' to clear the old build.

     ![Bildschirmfoto 2023-05-01 um 09 18 49](https://user-images.githubusercontent.com/30198737/235422081-b5df0b4b-5b1a-4d21-982e-858ef91cf898.png)

    Because your installation uses the old wbusmeter component.
    ```log
        [08:53:43][C][wmbus:312]: wM-Bus v1.4.8:`
        [08:53:43][C][wmbus:342]:   Available drivers:  amiplus, apator08, apator162, apatoreitn, bmeters, elf, evo868, fhkvdataiii, hydrocalm3, itron, izar, mkradio3, mkradio4, qheat, qwater, ultrimis, unismart, vario451
      NEW:  --> [09:06:41][C][wmbus:314]:   Available drivers:  amiplus, apator08, apator162, apatoreitn, bmeters, elf, evo868, fhkvdataiii, hydrocalm3, itron, izar, mkradio3, mkradio4, qheat, qwater, sharky774, topaseskr, ultrimis, unismart, vario451
    ```

4. Check your CC1101 connection, be shure that:

    ```
    GDO0 Pin: GPIO5 --> connected to gdo0_pin (CC1101)
    GDO2 Pin: GPIO4  --> connected to gdo2_pin (CC1101)
    ```
    If they are wrong (swapped), then no values come.

**Comment by Freeman656** [comment]
All done. Keep in mind, I'm still using the ModeMCUv3 right now, that's why the board is on esp01_1m.
Still the same result with the following wiring :

mosi_pin: GPIO13
miso_pin: GPIO12
clk_pin: GPIO14
cs_pin: GPIO15
gdo0_pin: GPIO05
gdo2_pin: GPIO04

![image](https://user-images.githubusercontent.com/60422888/235426738-340d9816-9909-4eae-b685-cb450e3ce0e6.png)

new logs :
[logs_water-meter-izar-nodemcu_logs.txt](https://github.com/zibous/ha-watermeter/files/11364273/logs_water-meter-izar-nodemcu_logs.txt)

**Comment by zibous** [comment]
HI,

I installed a trial version on a NodeMCU V3  without C1101:
> **board: nodemcuv2** instead of board board = esp01_1m**

```
Processing water-meter-nodemcu (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266@3.2.0)

11:19:26][C][wmbus:284]: wM-Bus v2.0.5:
[11:19:26][C][wmbus:301]:   CC1101 SPI bus:
[11:19:26][C][wmbus:302]:     MOSI Pin: GPIO13
[11:19:26][C][wmbus:303]:     MISO Pin: GPIO12
[11:19:26][C][wmbus:304]:     CLK Pin:  GPIO14
[11:19:26][C][wmbus:305]:     CS Pin:   GPIO15
[11:19:26][C][wmbus:306]:     GDO0 Pin: GPIO5
[11:19:26][C][wmbus:307]:     GDO2 Pin: GPIO4
[11:19:26][E][wmbus:320]:   Check connection to CC1101!  <-- ERROR !
```

![CC1101-868mhz-radio-module-pinout](https://user-images.githubusercontent.com/30198737/235436049-d10eb867-3db7-45fb-950a-36d43649855e.jpg)


If the C1101 had no voltage or the other connections were not available, then the error message would appear:
`Check connection to CC1101! `. You can test it by simply removing wires

>The water sensor is underground about 50cm, and the D1mini about 20m from it in the house 

Or everything works perfectly, only the distance to the water meter is too great. For me it's 6m in the basement and thick concrete walls in between. I know that there are several water meters at my position, but I only get 2 more that are in the immediate vicinity (8 - 10m). I can't get the others that are further away.

**Comment by Freeman656** [comment]
OK, so I tried removing the supply wires and I get the 'Check connection' error in the logs, so it seems that the CC1101 is recognized when everything is plugged into correctly.
I also double checked the wiring which is fine, the changed the board name.
Still nothing I move the CC1101 a bit closer , it's now around 20m in open air, with the sensor meter still underground, but I won't be able to do much for this problem :)
Next step is to try getting even closer, maybe just above the sensor but I'm not sure I'll get wifi connection that far away.
I'll let you know.

**Comment by zibous** [comment]
Hi

> Next step is to try getting even closer, maybe just above the sensor but I'm not sure I'll get wifi connection that far away.
> I'll let you know.

O.k. 20m are already a challenge for a WLAN connection.  In addition, the WLAN power interferes with the 868Mhz traffic. 
I removed the CC1101 with longer cables from the device.

I ordered an antenna. Will test how the range increases...
https://amzn.eu/d/itdbwwz

**Comment by zibous** [comment]
**Testcase NodeMCU V3**

![nodemcu_cc1101](https://user-images.githubusercontent.com/30198737/235466920-6ffdd3b3-1399-4906-9b7b-953d5f1750fd.jpg)



![esphome_nodemcu](https://user-images.githubusercontent.com/30198737/235466937-0cc716dc-cc37-459d-93f7-27b0ec16649a.png)

> NOTE: When i connect the device to the Homeassistant i get the JSON Errors.

```yaml
---
## ------------------------------------------------------------------
## WMBUS NODEMCU V3 + CC1101 for Diehl IZAR RC 868 I R4 PL
##
## usage:  1. Using Homassistant API (discovery + devices)
##         2. Using HTTP Post to service server
##         3. Using wmbusmeters i a pipe
##
## This version shows data from the definded watermeter.
## Uses the watermeterID from the secrets.yaml file.
##
## WEBUI: http://water-meter.local
##
## Remark:
##   When device is connected to HA:   reboots with JSON Errors.
## ------------------------------------------------------------------
substitutions:
  device_name_short: "water-meter"
  device_description: "Wasserzähler Wemos D1 Mini, CUL - CC1101, IZAR module (Diehl IZAR RC 868 I R4 PL (SzczepanLeon) - my Watermeter"
  update_interval: 60s

  log_level: "DEBUG"
  appversion: "2.0.5"

  domain: !secret domain
  service_url: !secret service_host
  service_enabled: "false"
  service: "izar.watermeter"

  # additional sensors
  disabled_addOns: "true"

# ----------------------------------------------------------------
# HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
# ----------------------------------------------------------------
esp8266:
  board: nodemcuv2
  restore_from_flash: true

## ----------------------------------------------------------------
## ESPHOME APPLICATION
## ----------------------------------------------------------------
esphome:
  name: ${device_name_short}
  comment: ${device_description}
  project:
    name: "OE9psj.wmbus-minid1-v1"
    version: ${appversion}
  build_path: ./build/${device_name_short}
  on_boot:
    # At this priority, pretty much everything should already be initialized.
    priority: -100.0
    then:
      - globals.set:
          id: boot_counter
          value: !lambda "return id(boot_counter)+=1;"
      - logger.log:
          level: INFO
          tag: "BOOT"
          format: "BOOTMESSAGE:${device_name_short} API is connected, Device ready!"
  on_shutdown:
    priority: 700
    then:
      - logger.log:
          level: INFO
          tag: "BOOT"
          format: "BOOTMESSAGE:${device_name_short} is down!"

## ----------------------------------------------------------------
## External components
## ----------------------------------------------------------------
external_components:
  # uses the latest version from SzczepanLeon
  # https://github.com/SzczepanLeon/esphome-components
  # You can make ESPHome check the repository every time by setting this option to 0s
  - source: github://SzczepanLeon/esphome-components@main
    refresh: 0s
    components: [wmbus]

  # use local component from
  # https://github.com/zdzichu6969/esphome-components
  - source:
      type: local
      path: custom_components
    components: [backup]

  # use local component from
  # https://github.com/TheStaticTurtle/esphome_syslog
  - source:
      type: local
      path: custom_components
    components: [syslog]

## ---------------------------------------------------
## syslog service
## ---------------------------------------------------
syslog:
  ip_address: !secret syslog_server
  port: !secret syslog_port
  min_level: DEBUG
  enable_logger: true

# ----------------------------------------------------------------
# Save your ESPHome device configuration in firmware and and
# recover it if you lost source files.
# ----------------------------------------------------------------
# Just download it from http://water-meter-izar.local/config.yaml
backup:
  auth:
    username: !secret web_username
    password: !secret web_password
  force_update: false

## ----------------------------------------------------------------
## Global variables
## ----------------------------------------------------------------
globals:
  - id: boot_counter
    type: int
    restore_value: yes
    initial_value: "0"

  - id: int_default
    type: int
    restore_value: no
    initial_value: "0"

  - id: float_default
    type: float
    restore_value: no
    initial_value: "0.00"

  - id: m3toliter
    type: float
    initial_value: "1000.00"
    restore_value: yes

  - id: last_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: current_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: hour_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: daily_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: yesterday_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: week_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: month_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: lastmonth_value
    type: float
    restore_value: yes
    initial_value: "0.00"

  - id: year_value
    type: float
    restore_value: yes
    initial_value: "0.00"

## ---------------------------------------------------
## WIFI Settings 3 wifis
## ---------------------------------------------------
wifi:
  networks:
    - ssid: !secret ssid3_name
      password: !secret ssid3_pswd
      priority: 0
    - ssid: !secret ssid1_name
      password: !secret ssid1_pswd
      priority: 1
    - ssid: !secret ssid2_name
      password: !secret ssid2_pswd
      priority: 2
  domain: !secret domain

## ---------------------------------------------------
## The captive portal component in ESPHome is a
## fallback mechanism for when connecting to the
## configured WiFi fails.
## ---------------------------------------------------
captive_portal:

logger:
  id: appslogger
  level: ${log_level}
  baud_rate: 0 #disable logging over uart

debug:
  update_interval: 5s

## ---------------------------------------------------
## OTA Updates
## ---------------------------------------------------
ota:
  password: !secret ota_pswd
  on_error:
    then:
      - logger.log:
          format: "OTA update error %d"
          args: ["x"]

## ---------------------------------------------------
## LOCAL WEBSERVER, local settings - no internet
## ---------------------------------------------------
web_server:
  port: 80
  version: 2
  local: true

## ---------------------------------------------------
# Enable Home Assistant API
## ---------------------------------------------------
# Homeassistant service call:
# service: esphome.water_meter_set_water_val
# data:
#  water_val_hour: 0.03
#  water_val_day: 0.248
#  water_val_yesterday: 0.178
#  water_val_week: 0.248
#  water_val_month: 1.94
#  water_val_year: 14.256
#  water_val_lastmonth: 9.59
## ---------------------------------------------------
api:
  id: espapiwm_v1
  port: 6053
  reboot_timeout: 0s
  services:
    - service: set_watermeter_data
      variables:
        water_val_hour: float
        water_val_day: float
        water_val_yesterday: float
        water_val_week: float
        water_val_month: float
        water_val_year: float
        water_val_lastmonth: float
      then:
        - globals.set:
            id: hour_value
            value: !lambda |-
              if((water_val_hour) and (water_val_hour)>0.001){
                ESP_LOGI("main", "Set hourly value to: %f", water_val_hour);
                return (water_val_hour);
              }else{
                ESP_LOGI("main", "Skip setting hourly value");
                return id(hour_value);
              };
              id(waterhour).publish_state(id(hour_value));

        - globals.set:
            id: daily_value
            value: !lambda |-
              if((water_val_day) and (water_val_day)>0.001){
                ESP_LOGI("main", "Set daily value to: %f", water_val_day);
                return (water_val_day);
              }else{
                ESP_LOGI("main", "Skip setting hourly value");
                return id(hour_value);
              };
              id(waterday).publish_state(id(daily_value));

        - globals.set:
            id: yesterday_value
            value: !lambda |-
              if((water_val_yesterday) and (water_val_yesterday)>0.001){
                ESP_LOGI("main", "Set yesterday value to: %f", water_val_yesterday);
                return (water_val_yesterday);
              }else{
                ESP_LOGI("main", "Skip setting yesterday value");
                return id(yesterday_value);
              };
              id(wateryesterday).publish_state(id(hour_value));

        - globals.set:
            id: week_value
            value: !lambda |-
              if((water_val_week) and (water_val_week)>0.001){
                ESP_LOGI("main", "Set weekly value to: %f", water_val_week);
                return (water_val_week);
              }else{
                ESP_LOGI("main", "Skip setting weekly value");
                return id(week_value);
              };
              id(waterweek).publish_state(id(week_value));

        - globals.set:
            id: month_value
            value: !lambda |-
              if((water_val_month) and (water_val_month)>0.001){
                ESP_LOGI("main", "Set last montj value to: %f", water_val_month);
                return (water_val_month);
              }else{
                ESP_LOGI("main", "Skip setting monthly value");
                return id(week_value);
              };
              id(watermonth).publish_state(id(month_value));

        - globals.set:
            id: lastmonth_value
            value: !lambda |-
              if((water_val_lastmonth) and (water_val_lastmonth)>0.001){
                ESP_LOGI("main", "Set last month value to: %f", water_val_lastmonth);
                return (water_val_lastmonth);
              }else{
                ESP_LOGI("main", "Skip setting last month value");
                return id(lastmonth_value);
              };
              id(waterlastmonth).publish_state(id(lastmonth_value));

        - globals.set:
            id: year_value
            value: !lambda |-
              if((water_val_year) and (water_val_year)>0.001){
                ESP_LOGI("main", "Set last yearly value to: %f", water_val_year);
                return (water_val_year);
              }else{
                ESP_LOGI("main", "Skip setting last yearly value");
                return id(week_value);
              };
              id(wateryear).publish_state(id(year_value));

        - logger.log:
            format: "All new Values set: hour: %.1f, day: %.1f, week: %.1f, month: %.1f, lastmonth: %.1f, year: %.1f"
            args:
              [
                "id(hour_value)",
                "id(daily_value)",
                "id(week_value)",
                "id(month_value)",
                "id(lastmonth_value)",
                "id(year_value)",
              ]

## ---------------------------------------------------
## SNTP Time server
## ---------------------------------------------------
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.at.pool.ntp.org
      - 0.pool.ntp.org
      - 1.pool.ntp.org

    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"

    # reset hourly value
    on_time:
      - seconds: 0
        minutes: 0
        then:
          - globals.set:
              id: hour_value
              value: "0.00"
          - lambda: id(waterhour).publish_state(id(hour_value));
          - logger.log: Reset value hour, starting next hour

      # reset daily value and set yesterday value
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: id(yesterday_value)=id(daily_value);
          - lambda: id(wateryesterday).publish_state(id(yesterday_value));
          - lambda: id(daily_value)=0.00;
          - lambda: id(waterday).publish_state(id(daily_value));
          - logger.log: Set yesterday value and reset value daily, starting new day

      # reset weekly value, start new week
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_week: MON
        then:
          - globals.set:
              id: week_value
              value: "0.00"
          - lambda: id(waterweek).publish_state(id(week_value));
          - logger.log: Reset value weekly, starting new week

      # reset monthly value and set last month value
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_month: 1
        then:
          - globals.set:
              id: month_value
              value: "0.00"
          - lambda: id(watermonth).publish_state(id(month_value));
          - lambda: |-
              if(id(waterdisplay).state){
                id(lastmonth_value)=id(waterdisplay).state;
              }
          - logger.log: Reset value monthly, starting new month

      # new year, reset yearly value
      - seconds: 0
        minutes: 0
        hours: 0
        days_of_month: 1
        months: JAN
        then:
          - globals.set:
              id: year_value
              value: "0.00"
          - lambda: id(wateryear).publish_state(id(year_value));
          - logger.log: Reset value yearly, starting new year

## ---------------------------------------------------
## Prepare for sending HTTP requests
## ---------------------------------------------------
http_request:
  id: http_request_data
  useragent: ${service}
  timeout: 10s

## ---------------------------------------------------
## Post resultdata to the service url
## ---------------------------------------------------
script:
  - id: post_device_state
    then:
      - if:
          condition:
            lambda: return "${service_enabled} =='true'";
          then:
            - logger.log: "Post new data to the ${service_url}${device_name_short}, service enabled: ${service_enabled}"
            - http_request.post:
                url: "${service_url}/${device_name_short}"
                verify_ssl: false
                headers:
                  Content-Type: application/json
                json: |-
                  root["device"] = "${device_name_short}";
                  root["waterdisplay"] = id(waterdisplay).state;
                  root["current"] = id(id(watercurrent)).state;
                  root["hour"] = id(waterhour).state;
                  root["day"] = id(waterday).state;
                  root["yesterday"] = id(wateryesterday).state;
                  root["week"] = id(waterweek).state;
                  root["month"] = id(watermonth).state;
                  root["lastmonth"] = id(waterhour).state;
                  root["year"] = id(wateryear).state;
                  root["bootcounter"] = id(bootcounter).state;
                  root["version"] = "${device_name_short} ${appversion}";
                  root["time"] = id(sntp_time).now().strftime("%Y-%m-%d %H:%M:%S");
                on_response:
                  then:
                    - lambda: |-
                        if (status_code == 200) {
                        } else {
                            ESP_LOGI ("http_post", "HTTP POST failed");
                        }

## ---------------------------------------------------
## WMBUS DEVICE D1MINI WEMOS --> CC1101
## ---------------------------------------------------
wmbus:
  mosi_pin: GPIO13  #D7  MOSI Attached to Hardware SPI controller MOSI SPI Interface
  miso_pin: GPIO12  #D6  MISO Attached to Hardware SPI controller MISO SPI Interface
  clk_pin: GPIO14   #D5  SCK  Attached to Hardware SPI controller CLK
  cs_pin: GPIO15    #D8  CSN  Attached to Hardware SPI controller, Controls Boot Mode; CS SPI Interface 10k Pull-Down, boot fails if pulled high !!!
  gdo0_pin: GPIO05  #D1  Clock output. High Impedance !
  gdo2_pin: GPIO04  #D2  FIFO status signals. High Impedance !

## ---------------------------------------------------
## SWITCHES
## ---------------------------------------------------
switch:
  # reset boot counter value
  - platform: template
    name: Reset Boot Counter
    turn_on_action:
      then:
        - lambda: |-
            id(boot_counter) = id(int_default);
            id(bootcounter).publish_state(id(boot_counter));
        - logger.log:
            level: INFO
            tag: "BOOT"
            format: "${device_name_short} reset boot counter o.k!"

  # reset all global vars
  - platform: template
    name: Reset values
    turn_on_action:
      then:
        - lambda: |-
            id(last_value) = id(float_default);
            id(boot_counter) = id(int_default);
            id(bootcounter).publish_state(id(boot_counter));
            id(current_value) = id(float_default);
            id(watercurrent).publish_state(id(current_value));
            id(hour_value) = id(float_default);
            id(waterhour).publish_state(id(hour_value));
            id(daily_value) = id(float_default);
            id(waterday).publish_state(id(daily_value));
            id(yesterday_value) = id(float_default);
            id(wateryesterday).publish_state(id(yesterday_value));
            id(week_value) = id(float_default);
            id(waterweek).publish_state(id(week_value));
            id(month_value) = id(float_default);
            id(watermonth).publish_state(id(month_value));
            id(lastmonth_value) = id(float_default);
            id(waterlastmonth).publish_state(id(lastmonth_value));
            id(year_value) = id(float_default);
            id(wateryear).publish_state(id(year_value));
        - logger.log: all values reset!

  - platform: restart
    name: "Restart"
    id: restart_switch

## ---------------------------------------------------
## SENSORS
## ---------------------------------------------------
sensor:
  - platform: wmbus
    # Meter ID (usually from sticker). Can be specified as decimal or hex.
    # only hex is working for my watermeter !
    # see: https://github.com/SzczepanLeon/esphome-components/issues/6
    # edit watermeterid in the secrets file
    meter_id: !secret watermeterId
    type: izar
    ## settings to add the watermeterid to the lqi, rssi and total_water_m3
    add_prefix: false

    # The LQI value reported by the CC1101 is a 7 bit unsigned number with a range from 0 to 127.
    # Note that a lower value indicates a better link.
    # The LQI of a received packet will be bad (higher number) when there is lot of interference.
    lqi:
      id: wmbus_cc1101_lqi
      name: "Wlan CC1101 LQI"
      entity_category: "diagnostic"

    # The RSSI value reported by the CC1101 is a 8 bit signed number with an effective
    # range from -138 dBm to -10.5 dBm when the CC1101 is operating around 868 MHz.
    # RSSI stands for received signal strength (power) indication (in dBm).
    # A higher value indicates higher power. (internal only)
    rssi:
      id: wmbus_cc1101_rssi

    total_water_m3:
      name: "Wasseruhr Anzeige"
      id: "waterdisplay"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      on_value:
        then:
          - lambda: |-
              ESP_LOGI("SENSOR", "Water Display value: %f, last value: %f", id(waterdisplay).state, id(last_value));
              if ((id(last_value) > 0.00) and (id(waterdisplay).state)>(id(last_value)) ) {
                id(current_value) = float( id(waterdisplay).state - id(last_value) ) * id(m3toliter);
                id(watercurrent).publish_state(id(current_value));
                id(hour_value)+=id(current_value);
                id(waterhour).publish_state(id(hour_value));
                id(daily_value)+=id(current_value);
                id(waterday).publish_state(id(daily_value));
                id(week_value)+=id(current_value);
                id(waterweek).publish_state(id(week_value));
                id(month_value)+=id(current_value);
                id(watermonth).publish_state(id(month_value));
                id(year_value)+=id(current_value);
                id(wateryear).publish_state(id(year_value));
                ESP_LOGI("SENSOR", "Set current value to %f litre and publish the data", id(watercurrent));
                if ( ${service_enabled} == true){
                  id(post_device_state).execute();
                }
              }else{
                id(current_value) = 0.00;
                id(watercurrent).publish_state(id(current_value));
                ESP_LOGI("SENSOR", "Reset current value to: %f", id(watercurrent));
              }
              id(last_value)=id(waterdisplay).state;

          - text_sensor.template.publish:
              id: watermeter_lastupdate
              state: !lambda |-
                char str[20];
                time_t currTime = id(sntp_time).now().timestamp;
                strftime(str, sizeof(str), "%Y-%m-%dT%H:%M:%S", localtime(&currTime));
                return (std::string) str;

  # water current
  - platform: template
    name: Wasser Aktuell
    id: "watercurrent"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: "measurement"
    device_class: "water"
    lambda: |-
      return (id(current_value));

  # water current hour
  - platform: template
    name: Wasser Stunde
    id: "waterhour"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: "water"
    lambda: |-
      return (id(hour_value));

  # water today
  - platform: template
    name: Wasser Tag
    id: "waterday"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    lambda: |-
      return (id(daily_value));

  # water yesterday
  - platform: template
    name: Wasser Gestern
    id: "wateryesterday"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    lambda: |-
      return (id(yesterday_value));

  # water current week
  - platform: template
    name: Wasser Woche
    id: "waterweek"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    lambda: |-
      return (id(week_value));

  # water current month
  - platform: template
    name: Wasser Monat
    id: "watermonth"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: "water"
    lambda: |-
      return (id(month_value));

  # water current year
  - platform: template
    name: Wasser Jahr
    id: "wateryear"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: "water"
    lambda: |-
      return (id(year_value));

  # water last month
  - platform: template
    name: Wasser letzer Monat
    id: "waterlastmonth"
    accuracy_decimals: 2
    unit_of_measurement: "L"
    state_class: "measurement"
    device_class: "water"
    lambda: |-
      return (id(lastmonth_value));

  # device boot counter
  - platform: template
    name: Boot counter
    id: bootcounter
    accuracy_decimals: 0
    state_class: "measurement"
    entity_category: "diagnostic"
    lambda: |-
      return (id(boot_counter));

  # device uptime human reading format  
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    update_interval: ${update_interval}
    unit_of_measurement: seconds
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

  # Wifi quality RSSI
  # only internal used (memory bug D1MINI ??)
  - platform: wifi_signal
    name: Wlan Signal
    id: wifi_signal_db
    update_interval: 60s
    internal: true
    entity_category: "diagnostic"

  # Wifi quality RSSI in percentage
  # # Received Signal Strength (RSSI) is a measure of incoherent (raw) RF power in a channel.
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "Wlan D1MINI Qualität"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  # CC1101 quality RSSI in percentage
  # Received Signal Strength (RSSI) is a measure of incoherent (raw) RF power in a channel.
  - platform: copy
    source_id: wmbus_cc1101_rssi
    name: "Wlan CC1101 RSSI"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"

  - platform: debug

    #  Reports the free heap size in bytes.
    free:
      name: "Heap Free"
      entity_category: "diagnostic"

    # Reports the fragmentation metric of the heap (0% is clean, more than ~50% is not harmless).
    fragmentation:
      name: "Heap Fragmentation"
      entity_category: "diagnostic"

    # Reports the largest contiguous free RAM block on the heap in bytes.
    block:
      name: "Heap Max Block"
      entity_category: "diagnostic"

    # Reports the longest time between successive iterations of the main loop.
    loop_time:
      name: "Loop Time"
      entity_category: "diagnostic"

## ---------------------------------------------------
## BINARY SENSOR
## ---------------------------------------------------
binary_sensor:
  # simulate led state
  - platform: template
    name: Status Led
    id: statusled
    entity_category: "diagnostic"
    lambda: "return id(current_value) > 0;"

## ---------------------------------------------------
## TEXT SENSOR
## ---------------------------------------------------
text_sensor:

  # device version
  # disabled for api (memory ??)
  - platform: version
    name: Version
    id: appver
    internal: ${disabled_addOns}
    entity_category: "diagnostic"

  # device online time
  # disabled for api (memory ??)
  - platform: template
    name: Online seit
    id: uptime_human
    internal: ${disabled_addOns}
    icon: mdi:clock-start
    entity_category: "diagnostic"

  # waterdisplay last update
  - platform: template
    name: Zählerstand aktualisiert
    id: watermeter_lastupdate
    icon: mdi:clock-start
    entity_category: "diagnostic"

  # device timestamp
  # disabled for api (memory ??)
  - platform: template
    name: Timestamp
    id: systime
    entity_category: "diagnostic"
    internal: ${disabled_addOns}
    lambda: char str[20];
      time_t currTime = id(sntp_time).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%dT%H:%M:%S", localtime(&currTime));
      return (std::string) str;

  - platform: debug

    # Reports the device information:
    device:
      name: "Device Info"
      entity_category: "diagnostic"
      internal: ${disabled_addOns}
    # Reports the last reboot reason in a human-readable form.

    reset_reason:
      name: "Reset Reason"
      entity_category: "diagnostic"

  # simple rest get message for all watermeter data
  # curl -i http://water-meter-izar.local/text_sensor/watermeterdata
  - platform: template
    id: watermeterdata
    update_interval: ${update_interval}
    internal: true
    lambda: |-
      char buf[512];
      sprintf(buf, "%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%.3f|%s",
             id(waterdisplay).state,
             id(current_value),
             id(hour_value),
             id(daily_value),
             id(yesterday_value),
             id(week_value),
             id(month_value),
             id(lastmonth_value),
             id(year_value),
             id(systime).state.c_str()
             );
      std::string s = buf;
      return s;

```

```
