### ISSUE TITLE
Multiple water meters with a single ESP

### ISSUE THREAD

**Issue by tomav** [zibous/ha-watermeter#15]
Hi @zibous, thanks for this project, works great! 👏

I was wondering if there was a way to collect data from 2 water meters (with different IDs) with a single ESP32?
I suppose it is but can't find an example.

Other question: have you noticed different data between what's on the physical water meter and the data retreived via RF?

Thanks.

**Comment by zibous** [comment]
Hi,

Add for each watermeter a `platform: wmbus` section with the `meter_id`
see: <https://github.com/zibous/ha-watermeter/blob/master/esphome/wm-d1mini-simple.yaml>

```
 - platform: wmbus
    # watermeter 1: nearly to mine
    meter_id: 0x43410778
    type: izar
    add_prefix: True
    # get the total watermter m3 from the wmbus telegram
    total_water_m3:
      name: "Watermeter"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter

  - platform: wmbus
    # watermeter 3: nearly to mine
    meter_id: 0x43890785
    type: izar
    add_prefix: True
    # get the total watermter m3 from the wmbus telegram
    total_water_m3:
      name: "Watermeter"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter
```

> Other question: have you noticed different data between what's on the physical water meter and the data retreived via RF?

For my IZAR no, same as with wmbusmeters.
