### ISSUE TITLE
CC1101-E07-900MBL-01

### ISSUE THREAD

**Issue by zibous** [zibous/ha-watermeter#23]
Hi @zibous,

Tell me if you want me to open a new issue.
I've received and tested a new E07-900MBL-01 rev v.1.1 to replace the CC1101 cards, tested 2 ESP32, and I still got the corruptions.

After some investigations, they only appear when calling 
```
wmbus:
  mosi_pin: GPIO23  ## SI:   braun   3: MOSI Attached to Hardware SPI controller MOSI SPI Interface
  miso_pin: GPIO19  ## SO:   grün    5: MISO Attached to Hardware SPI controller MISO SPI Interface
  clk_pin: GPIO18   ## SCLK: violett 4: SCK  Attached to Hardware SPI controller CLK
  cs_pin: GPIO05    ## CSN:  orange  8: CSN  Attached to Hardware SPI controller
  gdo0_pin: GPIO16  ## GD00: gelb    7: RX Clock output. High Impedance !
  gdo2_pin: GPIO17  ## GD02: weiss   6: TX FIFO status signals. High Impedance !
  log_unknown: False
```

I've built the testing code with Web ESP Home and from Docker container, then it can't be related to the compiler.
The pins are good, are I've tested providing power to the network card by the integrated USB or from 3.3V of ESP32.
Cables are all brand new too.

Here is the wired setup
![20231020_213411](https://github.com/zibous/ha-watermeter/assets/8233121/0326c518-bad3-4e40-8b37-a7a2cac7f353)

By any chance, may you have another idea?

_Originally posted by @Flow76320 in https://github.com/zibous/ha-watermeter/issues/21#issuecomment-1773297937_
