### ISSUE TITLE
Blank web page with "200 OK" return

### ISSUE THREAD

**Issue by mickaelBert** [zibous/ha-watermeter#31]
HI, 

I'm not very familiar with ESPhome deployement. 
I have trie a lot of yaml (wm-esp32-simple, wm-esp32-test, ...) from your gihtub and i cannot get the webserver page to see the value or log information. I must be forgetting something :s

here is the url form the esp after deployment : 
![Capture d’écran 2023-12-12 à 10 24 35](https://github.com/zibous/ha-watermeter/assets/101428259/2639af73-ce41-4b7e-b71f-8c11774b2bc6)

here is the yaml used (but i have the same result after a lot of yaml test configuration)
[test.yaml.txt](https://github.com/zibous/ha-watermeter/files/13646246/test.yaml.txt)
i tried some configuration on webserver : local = true or false, etc. nothing help me. In all the case, i get the webserver with a blanck page and OK 200 text. 

here is the last deployment on esp32
[logs_test_run.txt](https://github.com/zibous/ha-watermeter/files/13646302/logs_test_run.txt)

Thanks for your help.

**Comment by zibous** [comment]
hi,

You use webserver `version 2` but the js_url is `version 1` :
```
## ---------------------------------------------------
## COMPONENT WEBSERVER
## ---------------------------------------------------
web_server:
  port: 80
  version: 2
  js_url: https://esphome.io/_static/webserver-v1.min.js
```

see: 
  https://esphome.io/components/web_server.html?highlight=webserver
  https://github.com/zibous/ha-watermeter/tree/master/esphome/webserver

Try this for a simple test:
You use webserver `version 2` but the js_url is `version 1` :
```
## ---------------------------------------------------
## COMPONENT WEBSERVER
## ---------------------------------------------------
web_server:
  port: 80
  version: 1
```
