### ISSUE TITLE
Web Server Parameter?

### ISSUE THREAD

**Issue by mauriziozito** [zibous/ha-watermeter#33]
Hi, sorry but I'm not clear on how to configure the webserver
Could you help me?
Even one example might suffice

thanks

**Comment by zibous** [comment]
see:
https://esphome.io/components/web_server.html?highlight=webserver
https://github.com/zibous/ha-watermeter/tree/master/esphome/webserver

Try this for a simple test:
```
## ---------------------------------------------------
## COMPONENT WEBSERVER
## ---------------------------------------------------
web_server:
  port: 80
  version: 1
```
