### ISSUE TITLE
Month and last month ?

### ISSUE THREAD

**Issue by patmtp35** [zibous/ha-watermeter#37]
hi,

worki,g like a charm since 2 weeks, but some thing strange,  as we pass on ferbruary, watermonth , last month and water display last month dosen't change . any idea ?

![image](https://github.com/zibous/ha-watermeter/assets/6410695/e173710c-bdde-4be9-addf-de8ea03b9ab4)

**Comment by zibous** [comment]
The following reasons could be: 

- You don't get any data from the water meter anymore. 
- The time component does not work properly because the history data (hour, day, monthly consumption) is created there.

see:

```yaml
## ---------------------------------------------------
## SNTP COMPONENT
## ---------------------------------------------------
time:
  - platform: sntp
    id: time_sntp
    timezone: Europe/Berlin
    servers:
      - !secret local_sntp
      - 0.at.pool.ntp.org
      - 0.pool.ntp.org
   ....... 
```

I would take a look at the log to see whether you receive data and how it is processed. 
```yaml
  ## logger settings
  log_level: "DEBUG"   # not that logging need memory, so in production mode use "WARN"
  log_wmbus: "VERBOSE"  # Loglevel for wmbus meters component
  log_baudrate: "0"   # use 115200 to enable serial UART port logging.

```

The status "Waterdisplay lastmonth" comes from the water meter and if it is 0, 
then it doesn't have it or you don't get any data. 

```yaml
    # get the last month total watermter m3 from the wmbus telegram
    last_month_total_water_m3:
      name: "Wasseruhr Anzeige letzter Monat"
      id: "waterdisplay_lastmonth"
      unit_of_measurement: "m³"
      state_class: total_increasing
      device_class: "water"
      accuracy_decimals: 3
      icon: mdi:counter
```
