### ISSUE TITLE
mehrere Devices

### ISSUE THREAD

**Issue by alkue1** [zibous/ha-watermeter#42]
Hi,

gibt es eine einfache Möglichkeit, gleich mehrere Zähler in einer Installation einzufügen?

Vielen Dank!

**Comment by zibous** [comment]
> gibt es eine einfache Möglichkeit, gleich mehrere Zähler in einer Installation einzufügen?
> 
> Vielen Dank!

Einfach pro Zähler `- platform: wmbus`einfügen und den `meter_id` und die benötigen Sensoren anfügen...

```
sensor:

  - platform: wmbus
     meter_id: !secret watermeterId1
     type: izar
     add_prefix: true
     rssi:
       name: "My RSSI"
     ... add more

  - platform: wmbus
     meter_id: !secret watermeterId2
     type: izar
     add_prefix: true
     rssi:
       name: "My RSSI"
     ... add more

- platform: wmbus
     meter_id: !secret watermeterId3
     type: izar
     add_prefix: true
     rssi:
       name: "My RSSI"
     ... add more
```
