### ISSUE TITLE
NameError: name 'getRequests' is not defined

### ISSUE THREAD

**Issue by Onepamopa** [zibous/ha-watermeter#58]
Start Server
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 71, in runRESTServer
    data = getESBHomeData(url=url,platform="textsensor", id="watermeterdata" )
  File "server.py", line 33, in getESBHomeData
    response = getRequests(url=strURL, errormessage=True)
NameError: name 'getRequests' is not defined

**Comment by zibous** [comment]
Error based on ESPHOME Webserer, wrong js_url.

Try:

```yaml
web_server:
  port: 80
  version: 3


Local usage:
## ------------------------------------------------------------------
## COMPONENT WEBSERVER
## The web_server component creates a simple web server on the node
## that can be accessed through any browser and a simple REST API.
## https://esphome.io/components/web_server.html
## local: Optional, boolean): Include supporting javascript locally allowing it to work without internet access. Defaults to false.
## ------------------------------------------------------------------
web_server:
  port: 80
  version: 3
  local: false
  js_url: "http://homassistant.local:8123/local/esp32/www.js"
  ```

Copy https://oi.esphome.io/v3/www.js to a folder in your webserver (homeassistant www/esp32) folder.
see https://esphome.io/components/web_server.html
